/* global GLOBAL */
GLOBAL.CONFIG = {
    DEBUG_MODE: 1, // 1, 2, 3, 4
    SESSION_CHECK_INACTIVITY_MINUTES: 5,
    SESSION_MAX_INACTIVITY_MINUTES: 15,
    GALAPAGOS_URL: 'http://52.70.122.198/create-standalone'
};